/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChecklistItem = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'NA' : IDL.Null,
    'Fail' : IDL.Null,
    'Pass' : IDL.Null,
    'Unchecked' : IDL.Null,
  }),
  'task' : IDL.Text,
  'section' : IDL.Text,
  'comment' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'month' : IDL.Nat,
  'submitted' : IDL.Bool,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'inspectedBy' : IDL.Text,
  'year' : IDL.Nat,
  'submittedAt' : IDL.Opt(IDL.Int),
  'systemId' : IDL.Text,
  'solarGenerationPerMonth' : IDL.Text,
  'notes' : IDL.Text,
  'items' : IDL.Vec(ChecklistItem),
  'solarGenerationUnits' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReport' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
  'deleteReport' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReport' : IDL.Func([IDL.Text], [Report], ['query']),
  'getReportPhotos' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReport' : IDL.Func([IDL.Text], [], []),
  'updateChecklistItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'NA' : IDL.Null,
          'Fail' : IDL.Null,
          'Pass' : IDL.Null,
          'Unchecked' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateReportMetadata' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateReportPhotos' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'NA' : IDL.Null,
      'Fail' : IDL.Null,
      'Pass' : IDL.Null,
      'Unchecked' : IDL.Null,
    }),
    'task' : IDL.Text,
    'section' : IDL.Text,
    'comment' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'month' : IDL.Nat,
    'submitted' : IDL.Bool,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'inspectedBy' : IDL.Text,
    'year' : IDL.Nat,
    'submittedAt' : IDL.Opt(IDL.Int),
    'systemId' : IDL.Text,
    'solarGenerationPerMonth' : IDL.Text,
    'notes' : IDL.Text,
    'items' : IDL.Vec(ChecklistItem),
    'solarGenerationUnits' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReport' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
    'deleteReport' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReport' : IDL.Func([IDL.Text], [Report], ['query']),
    'getReportPhotos' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReport' : IDL.Func([IDL.Text], [], []),
    'updateChecklistItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'NA' : IDL.Null,
            'Fail' : IDL.Null,
            'Pass' : IDL.Null,
            'Unchecked' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateReportMetadata' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateReportPhotos' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };