/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChecklistItem {
  'id' : string,
  'status' : { 'NA' : null } |
    { 'Fail' : null } |
    { 'Pass' : null } |
    { 'Unchecked' : null },
  'task' : string,
  'section' : string,
  'comment' : string,
}
export interface Report {
  'id' : string,
  'month' : bigint,
  'submitted' : boolean,
  'clientName' : string,
  'date' : string,
  'createdAt' : bigint,
  'inspectedBy' : string,
  'year' : bigint,
  'submittedAt' : [] | [bigint],
  'systemId' : string,
  'solarGenerationPerMonth' : string,
  'notes' : string,
  'items' : Array<ChecklistItem>,
  'solarGenerationUnits' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReport' : ActorMethod<[bigint, bigint], string>,
  'deleteReport' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReport' : ActorMethod<[string], Report>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listReports' : ActorMethod<[], Array<Report>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitReport' : ActorMethod<[string], undefined>,
  'updateChecklistItem' : ActorMethod<
    [
      string,
      string,
      { 'NA' : null } |
        { 'Fail' : null } |
        { 'Pass' : null } |
        { 'Unchecked' : null },
      string,
    ],
    undefined
  >,
  'updateReportMetadata' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];